{{- if .Values.podDisruptionBudget.create -}}
apiVersion: {{ include "gcp-idleness-exporter.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "gcp-idleness-exporter.fullname" . }}
  labels:
    {{- include "gcp-idleness-exporter.labels" . | nindent 4 }}
    {{- with .Values.customLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.podDisruptionBudget.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end  }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end  }}
  selector:
    matchLabels: 
    {{- include "gcp-idleness-exporter.selectorLabels" . | nindent 6 }}
{{- end }}
