apiVersion: v1
kind: Service
metadata:
  name: {{ include "gcp-idleness-exporter.fullname" . }}
  labels:
    {{- include "gcp-idleness-exporter.labels" . | nindent 4 }}
    {{- with .Values.customLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "gcp-idleness-exporter.selectorLabels" . | nindent 4 }}
